import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import Navbar from "../pages/component/navbar";
import Info from "../pages/component/info";

export default function Home() {
  return (
    <div>
      <div className={styles.container}>
        <Head>
          <title>Physiotherapie Dreigold</title>
          <meta
            name="description"
            content="Generated by create Romulo Galiao"
          />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Navbar />
        <main className={styles.main}>
          <h1>Deine Besserung beginnt hier</h1>
          <a className={styles}> Termin vereinbaren</a>
        </main>
      </div>
      <Info />
      <footer className={styles.footer}>footer</footer>
    </div>
  );
}
